apiVersion: v1
kind: ConfigMap
metadata:
  name: dataease-application
data:
  application.yml: |
    server:
      tomcat:
        connection-timeout: 70000
      servlet:
        context-path: 
    spring:
      servlet:
        multipart:
          max-file-size: 500MB
          max-request-size: 500MB
      datasource:
        url: jdbc:mysql://mysql-de-v2:3306/dataease?
        username: root
        password: Password123@mysql
    dataease:
      login_timeout: 480
      apisix-api:
        domain: http://apisix:9180
        key: d2e1a12576104c0ba002181940cb891
      selenium-server: http://de-selenium:4444/wd/hub
      export:
        views:
          limit: 100000
        dataset:
          limit: 100000
      origin-list: http://localhost:8000
    task:
      executor:
        address: http://sync-task-actuator:9001
        log:
          path: /opt/dataease2.0/logs/sync-task/task-handler-log

  config.yml: |
    apisix:
      node_listen: 9080              # APISIX listening port
      enable_ipv6: false

      enable_control: true
      control:
        ip: "0.0.0.0"
        port: 9092

    deployment:
      admin:
        allow_admin:
          - 0.0.0.0/0

        admin_key:
          - name: "admin"
            key: d2e1a12576104c0ba002181940cb8918
            role: admin

      etcd:
        host:
          - "http://apisix-etcd:2379"
        prefix: "/apisix"
        timeout: 30