{{ if and (eq .Values.DataEase.engine_mode "enterprise") .Values.apisix.enabled }}  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.apisix.host}}
spec:
  replicas: {{.Values.apisix.replicas}}
  serviceName: {{.Values.apisix.host}}
  selector:
    matchLabels:
      app: {{.Values.apisix.host}}
  template:
    metadata:
      labels:
        app: {{.Values.apisix.host}}
    spec:
      containers:
        - name: {{.Values.apisix.host}}
          image: {{.Values.common.imagePrefix}}{{.Values.apisix.image}}:{{.Values.apisix.imageTag}}
          imagePullPolicy: {{.Values.common.imagePullPolicy}}
          resources:
            limits:
              cpu: {{.Values.apisix.resourceLimits.cpu}}
              memory: {{.Values.apisix.resourceLimits.memory}}
            requests:
              memory: 200Mi
              cpu: 0.2
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: apisix-1  
              containerPort: 9180
            - name: apisix-2 
              containerPort: 9080
            # - name: apisix-3  
            #   containerPort: 9091
            # - name: apisix-4  
            #   containerPort: 9443
            # - name: apisix-5  
            #   containerPort: 9092
          volumeMounts:
            - mountPath: /usr/local/apisix/conf/config.yaml
              name: opt-apisix-config
              subPath: config.yml
            - mountPath: /usr/local/apisix/logs
              name: apisix-logs
            - mountPath: /usr/local/apisix/apisix/plugins/cas-auth.lua
              name: cas-auth
              subPath: cas-auth.lua
            - mountPath: /usr/local/apisix/apisix/plugins/openid-connect.lua
              name: openid-connect
              subPath: openid-connect.lua
            - mountPath: /usr/local/apisix/apisix/plugins/hmac-auth.lua
              name: hmac-auth
              subPath: hmac-auth.lua
      {{if ne (.Values.common.imagePullSecrets | default "nil") "nil"}}
      imagePullSecrets:
        - name: {{.Values.common.imagePullSecrets}}
      {{ end }}
      volumes:
        - name: opt-apisix-config
          configMap:
            defaultMode: 420
            name: dataease-application
        - name: apisix-logs
          persistentVolumeClaim:
            claimName: apisix-logs
        - name: cas-auth
          configMap:
            defaultMode: 420
            name: apisix-cas-auth
        - name: openid-connect
          configMap:
            defaultMode: 420
            name: apisix-openid-connect
        - name: hmac-auth
          configMap:
            defaultMode: 420
            name: apisix-hmac-auth
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.apisix.host}}
  labels:
    app: {{.Values.apisix.host}}
spec:
  clusterIP: None
  selector:
    app: {{.Values.apisix.host}}
  ports:
    - name: tcp-9180  
      port: 9180  
      protocol: TCP  
    - name: tcp-9080  
      port: 9080  
      protocol: TCP  
    # - name: tcp-9091  
    #   port: 9091  
    #   protocol: TCP  
    # - name: tcp-9443  
    #   port: 9443  
    #   protocol: TCP  
    # - name: tcp-9092  
    #   port: 9092  
    #   protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dataease-apisix-nodeport
  labels:
    app: {{.Values.apisix.host}}
spec:
  type: NodePort
  selector:
    app: {{.Values.apisix.host}}
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: {{.Values.apisix.nodeport_port}}
{{end}}