{{if .Values.DataEase.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.common.dataease.host}}
spec:
  replicas: {{.Values.DataEase.replicas}}
  selector:
    matchLabels:
      app: {{.Values.common.dataease.host}}
  template:
    metadata:
      labels:
        app: {{.Values.common.dataease.host}}
    spec:
      containers:
        - name: dataease
          image: {{.Values.common.imagePrefix}}{{.Values.DataEase.image}}:{{.Values.DataEase.imageTag}}
          imagePullPolicy: {{.Values.common.imagePullPolicy}}
          resources:
            limits:
              cpu: {{.Values.DataEase.resourceLimits.cpu}}
              memory: {{.Values.DataEase.resourceLimits.memory}}
            requests:
              memory: 512Mi
              cpu: 0.4
          env:
            - name: JAVA_OPTIONS
              value: {{.Values.DataEase.java_options}}          
          ports:
            - name: tcp
              containerPort: 8100
          volumeMounts:
            - mountPath: /opt/apps/config/application.yml
              name: opt-dataease2-app
              subPath: application.yml
            - mountPath: /opt/dataease2.0/logs
              name: opt-dataease2-logs
            - mountPath: /opt/dataease2.0/data/static-resource
              name: opt-dataease2-resource
            - mountPath: /opt/dataease2.0/cache
              name: opt-dataease2-cache             
            - mountPath: /opt/dataease2.0/data/geo
              name: opt-dataease2-geo
            - mountPath: /opt/dataease2.0/data/appearance
              name: opt-dataease2-appearance
            - mountPath: /opt/dataease2.0/data/exportData
              name: opt-dataease2-exportdata 
            - mountPath: /opt/dataease2.0/data/plugin
              name: opt-dataease2-plugin
            - mountPath: /opt/dataease2.0/data/font
              name: opt-dataease2-font
            - mountPath: /opt/dataease2.0/data/i18n
              name: opt-dataease2-i18n
            - mountPath: /opt/dataease2.0/data/map
              name: opt-dataease2-map
      {{if ne (.Values.common.imagePullSecrets | default "nil") "nil"}}
      imagePullSecrets:
        - name: {{.Values.common.imagePullSecrets}}
      {{ end }}
      volumes:
        - name: opt-dataease2-app
          configMap:
            name: dataease-application
            defaultMode: 420
        - name: opt-dataease2-logs
          persistentVolumeClaim:
            claimName: dataease2-logs
        - name: opt-dataease2-resource
          persistentVolumeClaim:
            claimName: dataease2-resource
        - name: opt-dataease2-cache
          persistentVolumeClaim:
            claimName: dataease2-cache
        - name: opt-dataease2-geo
          persistentVolumeClaim:
            claimName: dataease2-geo
        - name: opt-dataease2-appearance
          persistentVolumeClaim:
            claimName: dataease2-appearance
        - name: opt-dataease2-exportdata
          persistentVolumeClaim:
            claimName: dataease2-exportdata
        - name: opt-dataease2-plugin
          persistentVolumeClaim:
            claimName: dataease2-plugin
        - name: opt-dataease2-font
          persistentVolumeClaim:
            claimName: dataease2-font
        - name: opt-dataease2-i18n
          persistentVolumeClaim:
            claimName: dataease2-i18n
        - name: opt-dataease2-map
          persistentVolumeClaim:
            claimName: dataease2-map
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.common.dataease.host}}
  labels:
    app: {{.Values.common.dataease.host}}
spec:
  clusterIP: None
  selector:
    app: {{.Values.common.dataease.host}}
  ports:
    - name: tcp-8100
      port: 8100
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dataease2-http
  labels:
    app: {{.Values.common.dataease.host}}
spec:
  type: NodePort
  selector:
    app: {{.Values.common.dataease.host}}
  ports:
  - port: 8100
    targetPort: 8100
    nodePort: {{.Values.common.dataease.nodeport_port}}
{{end}}
