{{ if and (eq .Values.DataEase.engine_mode "enterprise") .Values.apisix.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apisix-etcd
spec:
  accessModes:
    - {{.Values.apisixetcd.accessModes}}
  resources:
    requests:
      storage: {{.Values.apisixetcd.size}}
  storageClassName: {{.Values.common.storageClass}}
{{end}}  
